=== DigitalExegete/xmlroff/codegen/codegen-info.dtd
<?xml encoding="utf-8" ?>
<!-- libfo -->
<!-- DTD for control file for dumping .c and .h files from XSL spec-->

<!-- Copyright (C) 2001-2006 Sun Microsystems                      -->
<!-- Copyright (C) 2007 Menteith Consulting Ltd                    -->
<!-- See COPYING for the status of this software.                  -->

<!--                    codegen-info                               -->
<!--                    Data controlling dumping of .c and .h
                        files from XSL spec.                       -->
<!ELEMENT  codegen-info (fos, properties)                            >


<!--                    fos                                        -->
<!--                    Information about formatting objects.      -->
<!ELEMENT  fos          (fo+)                                        >


<!--                    fo                                         -->
<!--                    Information about one formatting object.   -->
<!ELEMENT  fo           (defines?, hdefines?, errors?)               >
<!--         name       Formatting object name
             parent-typeParent object type, e.g., 'table-part'.
             mixed      Whether or not the formatting object contains
                        mixed content.
             area       Whether or not the formatting object
                        generates areas.
             inline     Whether or not the formatting object
                        generates inline areas.
             block      Whether or not the formatting object
                        generates block areas.
             neutral    Whether or not the formatting object
                        generates neutral areas.
             reference  Whether or not the formatting object
                        generates reference areas.
             validate   Function that validates formatting object's
                        properties.
             validate-content
                        Function that validates formatting object's
                        content.                                   -->
<!ATTLIST  fo
             name       CDATA                              #REQUIRED
             parent-type
                        CDATA                              #IMPLIED
             mixed      (yes | no)                         "no"
             area       (yes | no)                         "no"
             inline     (yes | no)                         "no"
             block      (yes | no)                         "no"
             neutral    (yes | no)                         "no"
             reference  (yes | no)                         "no"
             validate   CDATA                              #IMPLIED
             validate-content
                        CDATA                              #IMPLIED  >


<!--                    defines                                    -->
<!--                    '#define' text to insert into a generated
                        .c file.                                   -->
<!ELEMENT  defines      (#PCDATA)                                    >


<!--                    hdefines                                   -->
<!--                    '#define' text to insert into a generated
                        .h file.                                   -->
<!ELEMENT  hdefines     (#PCDATA)                                    >



<!--                    errors                                     -->
<!--                    Errors defined for the formatting object
                        or property.                               -->
<!ELEMENT  errors       (error+)                                     >



<!--                    error                                      -->
<!--                    One error defined for a formatting object
                        or property.                               -->
<!ELEMENT  error        EMPTY                                        >
<!--         code       Error code
             message    Error message.                             -->
<!ATTLIST  error
             code       CDATA                              #REQUIRED
             message    CDATA                              #REQUIRED >


<!--                    properties                                 -->
<!--                    Information about properties.              -->
<!ELEMENT  properties   (property+)                                  >



<!--                    property                                   -->
<!--                    Information about a single property.       -->
<!ELEMENT  property     (defines?, hdefines?, errors?)               >
<!--         name       Property name
             type       Expected datatype of resolved property value.
             is-text-property
                        Whether or not the property is a text
                        property.
             init-value Expression to set the property's initial
                        value.
             resolve-enum
                        Function that resolves property's enumeration
                        tokens.
             validate   Function that validates property's resolved
                        value.
             expr-eval  Function that evaluates property expressions.
                                                                   -->
<!ATTLIST  property
             name       CDATA                              #REQUIRED
             type       (keep | length-conditional | length-range |
                         space)                            #IMPLIED
             is-text-property
                        (yes | no)                         "no"
             init-value CDATA                              #IMPLIED
             resolve-enum
                        CDATA                              #IMPLIED
             validate   CDATA                              #IMPLIED
             expr-eval  CDATA                              #IMPLIED  >

=== DigitalExegete/xmlroff/codegen/codegen-info.xml
<!DOCTYPE codegen-info SYSTEM "codegen-info.dtd">
<!-- libfo -->
<!-- Control file for dumping .c and .h files from XSL spec -->

<!-- Copyright (C) 2001-2006 Sun Microsystems -->
<!-- Copyright (C) 2007-2008 Menteith Consulting Ltd -->
<!-- See COPYING for the status of this software. -->

<codegen-info>
<fos>
<fo name="basic-link"
    inline="yes"
    mixed="yes"
    cbpbp="yes"/>
<fo name="bidi-override"
    inline="yes"
    mixed="yes">
<defines>
/* PDF = U+202C
 *     = 0010 0000 0010 1100 (UTF-16)
 *     = zzzz yyyy yyxx xxxx
 *     = 1110zzzz 10yyyyyy 10xxxxxx (UTF-8)
 *     = 11100010 10000000 10101100 (UTF-8)
 *     = 11 100 010  10 000 000  10 101 100 (UTF-8)
 *     = \342\200\254 (UTF-8)
 */
#define FO_UTF8_STR_PDF		"\342\200\254"	/* U+202C */
#define FO_UTF8_STR_RLO		"\342\200\256"	/* U+202E */
#define FO_UTF8_STR_LRO		"\342\200\255"	/* U+202D */
#define FO_UTF8_STR_RLE		"\342\200\253"	/* U+202B */
#define FO_UTF8_STR_LRE		"\342\200\252"	/* U+202A */
</defines>
</fo>
<fo name="block"
    parent-type="marker-parent"
    block="yes"
    mixed="yes"
    cbpbp="yes"/>
<fo name="block-container"
    parent-type="marker-parent"
    block="yes"
    reference="yes"
    area="yes"
    cbpbp="yes"/>
<fo name="character"
    validate-content="fo_fo_validate_content_empty"
    inline="yes"
    cbpbp="yes"/>
<fo name="external-graphic"
    validate-content="fo_fo_validate_content_empty"
    inline="yes"
    cbpbp="yes"/>
<fo name="flow"
    parent-type="marker-parent"
    cbpbp="yes"/>
<fo name="initial-property-set"
    validate-content="fo_fo_validate_content_empty"
    cbpbp="yes"/>
<fo name="inline"
    parent-type="marker-parent"
    inline="yes"
    mixed="yes"
    cbpbp="yes"/>
<fo name="inline-container"
    parent-type="marker-parent"
    inline="yes"
    reference="yes"
    cbpbp="yes"/>
<fo name="instream-foreign-object"
    inline="yes"
    cbpbp="yes"/>
<fo name="leader"
    inline="yes"
    mixed="yes"
    cbpbp="yes"/>
<fo name="list-block"
    parent-type="marker-parent"
    block="yes"
    cbpbp="yes"/>
<fo name="list-item"
    parent-type="marker-parent"
    cbpbp="yes"/>
<fo name="list-item-body"
    parent-type="marker-parent"/>
<fo name="marker"
    mixed="yes"/>
<fo name="multi-case"
    mixed="yes"/>
<fo name="multi-toggle"
    inline="yes"
    mixed="yes"/>
<fo name="page-number"
    inline="yes"
    cbpbp="yes"/>
<fo name="page-number-citation"
    inline="yes"
    cbpbp="yes"/>
<fo name="page-sequence" area="yes"/>
<fo name="region-after"
    parent-type="region"
    validate-content="fo_fo_validate_content_empty"
    reference="yes"
    cbpbp="yes"/>
<fo name="region-before"
    parent-type="region"
    validate-content="fo_fo_validate_content_empty"
    reference="yes"
    cbpbp="yes"/>
<fo name="region-body"
    parent-type="region"
    validate-content="fo_fo_validate_content_empty"
    reference="yes"
    cbpbp="yes"/>
<fo name="region-end"
    parent-type="region"
    validate-content="fo_fo_validate_content_empty"
    reference="yes"
    cbpbp="yes"/>
<fo name="region-start"
    parent-type="region"
    validate-content="fo_fo_validate_content_empty"
    reference="yes"
    cbpbp="yes"/>
<fo name="simple-page-master"
    reference="yes"/>
<fo name="static-content"
    validate-content="fo_fo_validate_content_block_plus"
    cbpbp="yes"/>
<fo name="table"
    parent-type="marker-parent"
    block="yes"
    reference="yes"
    cbpbp="yes">
<defines>
#define fo_table_make_column_hash_key(column_number,number_columns_spanned) \
           (((column_number) &lt;&lt; 16) + (number_columns_spanned))

GType
fo_enum_table_layout_method_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { FO_ENUM_TABLE_LAYOUT_METHOD_UNKNOWN, "FO_ENUM_TABLE_LAYOUT_METHOD_UNKNOWN", "unknown" },
        { FO_ENUM_TABLE_LAYOUT_METHOD_AUTOMATIC, "FO_ENUM_TABLE_LAYOUT_METHOD_AUTOMATIC", "automatic" },
        { FO_ENUM_TABLE_LAYOUT_METHOD_FIXED, "FO_ENUM_TABLE_LAYOUT_METHOD_FIXED", "fixed" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("FoEnumTableLayoutMethod", values);
    }
  return etype;
}
</defines>
<hdefines>
typedef enum {
  FO_ENUM_TABLE_LAYOUT_METHOD_UNKNOWN,
  FO_ENUM_TABLE_LAYOUT_METHOD_AUTOMATIC,
  FO_ENUM_TABLE_LAYOUT_METHOD_FIXED
} FoEnumTableLayoutMethod;

GType fo_enum_table_layout_method_get_type (void);
#define FO_TYPE_ENUM_TABLE_LAYOUT_METHOD fo_enum_table_layout_method_get_type ()
</hdefines>
<errors>
<error code="LAYOUT_METHOD_UNKNOWN" message="Table layout method is unknown."/>
<error code="FIXED_NO_COLUMN" message="Table layout method is fixed but no 'fo:table-column's specified."/>
<error code="MISSING_COLUMN" message="No 'fo:table-column' for column number '%d'."/>
<error code="WIDTH_NOT_LENGTH" message="'column-width' expression is not a length: '%s'"/>
<error code="NO_AREA" message="No area associated with 'fo:table'."/>
<error code="SPANNING_CELLS_FILL_ROW" message="Spanning table cells fill entire row."/>
<error code="AUTOMATIC_NOT_SUPPORTED" message="Automatic table layout is not supported.  Falling back to fixed table layout."/>
</errors>
</fo>
<fo name="table"
    cbpbp="yes"/>
<fo name="table-and-caption"
    parent-type="marker-parent"
    block="yes"
    cbpbp="yes"/>
<fo name="table-body"
    parent-type="table-part"
    validate-content="fo_table_validate_content_table_row_table_cell"
    area="yes"
    cbpbp="yes"/>
<fo name="table-caption"
    parent-type="marker-parent"
    validate-content="fo_fo_validate_content_block_plus"
    reference="yes"
    cbpbp="yes"/>
<fo name="table-cell"
    parent-type="marker-parent"
    validate-content="fo_fo_validate_content_block_plus"
    reference="yes"
    area="yes"
    cbpbp="yes"/>
<fo name="table-column"
    validate-content="fo_fo_validate_content_empty"
    cbpbp="yes">
<errors>
<error code="FIXED_NO_WIDTH" message="'column-width' property must be specified when fixed table layout method is used."/>
</errors>
</fo>
<fo name="table-footer"
    parent-type="table-part"
    validate-content="fo_table_validate_content_table_row_table_cell"
    area="yes"
    cbpbp="yes"/>
<fo name="table-header"
    parent-type="table-part"
    validate-content="fo_table_validate_content_table_row_table_cell"
    area="yes"
    cbpbp="yes"/>
<fo name="table-row"
    parent-type="marker-parent"
    area="yes"
    cbpbp="yes"/>
<fo name="title"
    mixed="yes"
    cbpbp="yes"/>
<fo name="wrapper"
    parent-type="marker-parent"
    neutral="yes"
    mixed="yes"/>
</fos>
<properties>
<property name="alignment-adjust" is-text-property="yes"/>
<property name="alignment-baseline" is-text-property="yes"/>
<property name="background-color"/>
<property name="background-image"/>
<property name="baseline-shift" is-text-property="yes"/>
<!--<property name="blank-or-not-blank"/>-->
<property name="block-progression-dimension" type="length-range"/>
<property name="border"
    resolve-enum="fo_property_util_resolve_wsc_enum"
    validate="fo_property_util_validate_wsc"
    expr-eval="fo_expr_wsc_eval" />
<property name="border-after-color"
    init-value="fo_property_util_get_color_initial ()"
    resolve-enum="fo_property_util_resolve_color_enum"
    validate="fo_property_util_validate_color"/>
<property name="border-after-precedence"
    resolve-enum="fo_property_util_resolve_force_enum"/>
<property name="border-after-style"
    init-value="fo_property_util_get_style_initial ()"
    resolve-enum="fo_property_util_resolve_style_enum"
    validate="fo_property_util_validate_style"/>
<property name="border-after-width"
    init-value="fo_property_util_get_width_initial ()"
    resolve-enum="fo_property_util_resolve_width_enum"
    validate="fo_property_util_validate_width"/>
<property name="border-before-color"
    init-value="fo_property_util_get_color_initial ()"
    resolve-enum="fo_property_util_resolve_color_enum"
    validate="fo_property_util_validate_color"/>
<property name="border-before-precedence"
    resolve-enum="fo_property_util_resolve_force_enum"/>
<property name="border-before-style"
    init-value="fo_property_util_get_style_initial ()"
    resolve-enum="fo_property_util_resolve_style_enum"
    validate="fo_property_util_validate_style"/>
<property name="border-before-width"
    init-value="fo_property_util_get_width_initial ()"
    resolve-enum="fo_property_util_resolve_width_enum"
    validate="fo_property_util_validate_width"/>
<property name="border-bottom"
    resolve-enum="fo_property_util_resolve_wsc_enum"
    validate="fo_property_util_validate_wsc"
    expr-eval="fo_expr_wsc_eval" />
<property name="border-bottom-color"
    init-value="fo_property_util_get_color_initial ()"
    resolve-enum="fo_property_util_resolve_color_enum"
    validate="fo_property_util_validate_color"/>
<property name="border-bottom-style"
    init-value="fo_property_util_get_style_initial ()"
    resolve-enum="fo_property_util_resolve_style_enum"
    validate="fo_property_util_validate_style"/>
<property name="border-bottom-width"
    init-value="fo_property_util_get_width_initial ()"
    resolve-enum="fo_property_util_resolve_width_enum"
    validate="fo_property_util_validate_width"/>
<property name="border-collapse"
    init-value="fo_enum_get_enum_by_nick (&quot;collapse&quot;)"/>
<property name="border-color"
    expr-eval="fo_expr_border_color_eval"
    resolve-enum="fo_property_util_resolve_color_transparent_enum"/>
<property name="border-end-color"
    init-value="fo_property_util_get_color_initial ()"
    resolve-enum="fo_property_util_resolve_color_enum"
    validate="fo_property_util_validate_color"/>
<property name="border-end-precedence"
    resolve-enum="fo_property_util_resolve_force_enum"/>
<property name="border-end-style"
    init-value="fo_property_util_get_style_initial ()"
    resolve-enum="fo_property_util_resolve_style_enum"
    validate="fo_property_util_validate_style"/>
<property name="border-end-width"
